// Code generated by blazor-gen. DO NOT EDIT.
package main

import "github.com/snowmerak/fiber-blazor/blazor"

type BindedCalcRequest struct {
	A int `form:"calc_a_dedb1437"`
	B int `form:"calc_b_dedb1437"`
}

const (
	bind_CalcRequest_A = "calc_a_dedb1437"
	bind_CalcRequest_B = "calc_b_dedb1437"
)

type BindingOfCalcRequest struct {
	*blazor.Binding
	A blazor.Field
	B blazor.Field
}

func GetBindingOfCalcRequest() BindingOfCalcRequest {
	b := blazor.NewBinding()
	return BindingOfCalcRequest{
		Binding: b,
		A: b.Field(bind_CalcRequest_A),
		B: b.Field(bind_CalcRequest_B),
	}
}

